#修改端口号
server:
  port: 8800
#配置数据库
database:
  url: jdbc:mysql://172.24.34.140:3306/deal?useUnicode=true&characterEncoding=utf-8
  #url: jdbc:mysql://localhost:3306/deal?useUnicode=true&characterEncoding=utf-8
  username: root
  password: root
spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  servlet:
    multipart:
      max-file-size: 3MB # 限制文件上传的大小
      enabled: true  #是否启用文件上传功能
#mybatis下划线转驼峰配置
mybatis:
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql语句
    map-underscore-to-camel-case: true

